name: Sync labels
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v4
      - uses: brpaz/action-label-syncer@master
        with:
          repository: |
              jerboa88/actions-sandbox
          token: ${{ secrets.GH_TOKEN }}
