name: Sync labels
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - .github/labels.yml
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      content: read
      issues: write
    steps:
      - uses: actions/checkout@v4
      - uses: micnncim/action-label-syncer@v1
        with:
          repository: |
              jerboa88/actions-test
          token: ${{ secrets.GH_TOKEN }}
